import os
import tempfile
from collections import defaultdict

import cv2
import gradio as gr
from ultralytics import YOLO


# ==========================================================
# MODEL
# ==========================================================

MODEL_PATH = "yolov8n.pt"

model = YOLO(MODEL_PATH)


# ==========================================================
# VEHICLE CO2 DATA
# ==========================================================

VEHICLE_DATA = {
    2: {"name": "Car", "co2": 120},
    3: {"name": "Motorcycle", "co2": 80},
    5: {"name": "Bus", "co2": 800},
    7: {"name": "Truck", "co2": 1000},
}


# ==========================================================
# VIDEO PROCESSING
# ==========================================================

def process_video(video_path):

    if video_path is None:
        raise gr.Error("Please upload a traffic video.")

    vehicle_counts = defaultdict(int)
    total_emissions = defaultdict(int)

    counted_track_ids = set()

    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        raise gr.Error("Unable to read uploaded video.")

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = max(1, int(cap.get(cv2.CAP_PROP_FPS)))

    output_path = os.path.join(
        tempfile.gettempdir(),
        "processed_traffic_output.mp4"
    )

    fourcc = cv2.VideoWriter_fourcc(*"mp4v")

    writer = cv2.VideoWriter(
        output_path,
        fourcc,
        fps,
        (width, height)
    )

    frame_count = 0

    while True:

        success, frame = cap.read()

        if not success:
            break

        frame_count += 1

        results = model.track(
            frame,
            persist=True,
            classes=[2, 3, 5, 7],
            verbose=False
        )

        if (
            results
            and results[0].boxes is not None
            and results[0].boxes.id is not None
        ):

            boxes = results[0].boxes.xyxy.cpu()
            track_ids = results[0].boxes.id.int().cpu().tolist()
            class_ids = results[0].boxes.cls.int().cpu().tolist()

            for box, track_id, class_id in zip(
                boxes,
                track_ids,
                class_ids
            ):

                if class_id not in VEHICLE_DATA:
                    continue

                vehicle_info = VEHICLE_DATA[class_id]

                vehicle_name = vehicle_info["name"]

                # Count each vehicle only once
                if track_id not in counted_track_ids:

                    counted_track_ids.add(track_id)

                    vehicle_counts[vehicle_name] += 1

                    total_emissions[vehicle_name] += (
                        vehicle_info["co2"]
                    )

                x1, y1, x2, y2 = map(int, box)

                cv2.rectangle(
                    frame,
                    (x1, y1),
                    (x2, y2),
                    (0, 255, 0),
                    2
                )

                label = f"{vehicle_name} | ID {track_id}"

                cv2.putText(
                    frame,
                    label,
                    (x1, y1 - 10),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.6,
                    (0, 255, 0),
                    2
                )

        writer.write(frame)

    cap.release()
    writer.release()

    total_co2 = sum(total_emissions.values())
    total_vehicles = sum(vehicle_counts.values())

    report = f"""
# Traffic Emission Analysis Report

### Summary

• Total Vehicles Detected: {total_vehicles}

• Total Estimated CO₂ Emission: {total_co2:,} g/km

---

## Vehicle Breakdown
"""

    for vehicle in ["Car", "Motorcycle", "Bus", "Truck"]:

        count = vehicle_counts.get(vehicle, 0)
        emission = total_emissions.get(vehicle, 0)

        report += f"""
### {vehicle}

- Count: {count}
- Estimated CO₂: {emission:,} g/km
"""

    report += f"""

---

## Processing Statistics

- Frames Processed: {frame_count}
- Unique Tracked Vehicles: {len(counted_track_ids)}

---

Generated by Traffic CO₂ Emission Monitor
"""

    return output_path, report


# ==========================================================
# UI
# ==========================================================

custom_css = """
.gradio-container {
    max-width: 1400px !important;
}
"""


with gr.Blocks(
    theme=gr.themes.Soft(),
    css=custom_css,
    title="Traffic CO₂ Emission Monitor"
) as demo:

    gr.Markdown(
        """
# 🚦 Traffic CO₂ Emission Monitor

### AI-Powered Smart Traffic Analytics

Detects vehicles using YOLOv8 tracking and estimates
traffic-related carbon emissions from uploaded videos.

Supported Classes:
- 🚗 Cars
- 🏍 Motorcycles
- 🚌 Buses
- 🚚 Trucks
"""
    )

    with gr.Row():

        with gr.Column(scale=1):

            video_input = gr.Video(
                label="Upload Traffic Video"
            )

            analyze_btn = gr.Button(
                "Analyze Traffic",
                variant="primary"
            )

        with gr.Column(scale=2):

            processed_video = gr.Video(
                label="Processed Video Output"
            )

    report_output = gr.Markdown(
        label="Emission Report"
    )

    analyze_btn.click(
        fn=process_video,
        inputs=video_input,
        outputs=[
            processed_video,
            report_output
        ]
    )

    gr.Markdown(
        """
---
Developed using YOLOv8 • OpenCV • Gradio • Hugging Face Spaces
"""
    )


if __name__ == "__main__":
    demo.launch()
